---
title: "HotFlash reduced data"
author: "Sandra Castro-Pearson"
date: "August 7, 2016"
output: pdf_document
---

```{r setup_dataload, include=FALSE, cache=TRUE}
library(stats)
library(ggplot2)

setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
file.names<-(Sys.glob("*.csv"))

#BRITISH NOT MIGRANT DATA
BM<-read.csv(file.names[1], stringsAsFactors = TRUE, header = TRUE)
BNM2<-read.csv(file.names[2], stringsAsFactors = TRUE, header = TRUE)

#delete women who were outliers in BNM (no umho above 1 ever recorded OR umho above 20 issues)
MAXIMUM<-apply(BNM2[,-1], 2, function(ncolumn) max(na.omit(ncolumn)))
outindexes<-c(which(MAXIMUM>20))

BNM2<-BNM2[,-outindexes]
```

```{r run_fcts_on_data, echo = FALSE, message = FALSE, warning = FALSE, fig.height=3}
setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
source("HF_analysis_functions.R")

#reduce data from 1 obs/sec to 1 obs every 10sec where the obs is the average of 10sec
index.list<-list(seq(from=1,to=nrow(BM),by=10), seq(from=1,to=nrow(BNM2),by=10))

reduced.BM<-apply(BM[,2:ncol(BM)], 2, function(x) reduction(x, index.list[[1]]))
reduced.BM<-data.frame(cbind(BM[index.list[[1]],1], reduced.BM))
reduced.BNM<-apply(BNM2[,2:ncol(BNM2)], 2, function(x) reduction(x, index.list[[2]]))
reduced.BNM<-data.frame(cbind(BNM2[index.list[[2]],1], reduced.BNM))

#Create smooth version of data
BM.filterwoman.list<-apply(reduced.BM[2:ncol(reduced.BM)], 2, function(x) get.smooth(reduced.BM[,1],x))
BNM.filterwoman.list<-apply(reduced.BNM[2:ncol(reduced.BNM)], 2, function(x) get.smooth(reduced.BNM[,1],x))

```


```{r stats_tables_BNM, echo = FALSE, message = FALSE, warning = FALSE, fig.height=3}
## Summary Statistics for British Non-Migrant Women
# setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
# source("HF_analysis_functions.R")
# library(knitr)
# 
# MEAN<-lapply(BNM.filterwoman.list, function(y) mean(na.omit(y[,3])))
# MEAN<-unlist(MEAN)
# MAXIMUM<-lapply(BNM.filterwoman.list, function(y) max(na.omit(y[,3])))
# MAXIMUM<-unlist(MAXIMUM)
# MEDIAN<-lapply(BNM.filterwoman.list, function(x) median(x[,3]))
# MEDIAN<-unlist(MEDIAN)
# BINNED.MODE<-lapply(BNM.filterwoman.list, function(x) get.binned.modes(x))
# BINNED.MODE<-unlist(BINNED.MODE)
# 
# mysummary<-data.frame(MAXIMUM, MEAN, MEDIAN, BINNED.MODE)
# write.csv(mysummary, file = "British.Not.Migrant.SummarySTATS.csv")
```


```{r stats_tables_BM, echo = FALSE, message = FALSE, warning = FALSE, fig.height=3}
## Summary Statistics for British Migrant Women
# setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
# source("HF_analysis_functions.R")
# library(knitr)
# 
# MEAN<-lapply(BM.filterwoman.list, function(y) mean(na.omit(y[,3])))
# MEAN<-unlist(MEAN)
# MAXIMUM<-lapply(BM.filterwoman.list, function(y) max(na.omit(y[,3])))
# MAXIMUM<-unlist(MAXIMUM)
# MEDIAN<-lapply(BM.filterwoman.list, function(x) median(x[,3]))
# MEDIAN<-unlist(MEDIAN)
# BINNED.MODE<-lapply(BM.filterwoman.list, function(x) get.binned.modes(x)) 
# BINNED.MODE<-unlist(BINNED.MODE)
# 
# mysummary2<-data.frame(MAXIMUM, MEAN, MEDIAN, BINNED.MODE)
# write.csv(mysummary2, file = "British.Migrant.SummarySTATS.csv")
```



```{r stats_plots, echo = FALSE, message = FALSE, warning = FALSE, fig.height=4}
##Plots of Statistics against clean data 
# blue - Maximum  
# red - Mean  
# green - Median  
# purple- Binned mode  
# setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
# source("HF_analysis_functions.R")
# plot.STATS(BNM.filterwoman.list, mysummary, reduced.BNM)
# plot.STATS(BM.filterwoman.list, mysummary2, reduced.BM)
```


```{r find_peaks, include = FALSE, message = FALSE, warning = FALSE}
#Find peaks
setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
source("findpeaks.R")
BM.peak.from.ksmooth<-lapply(BM.filterwoman.list, function(x) find.peaks(x))
BNM.peak.from.ksmooth<-lapply(BNM.filterwoman.list, function(x) find.peaks(x))
# BM.peak.from.ksmooth=list()
# for (bmcount in 1:length(BM.filterwoman.list)) {
#   BM.peak.from.ksmooth[[bmcount]]<-find.peaks(BM.filterwoman.list[[bmcount]])
# }
# 


setwd("c:/Users/pearsons0519/Documents/Summer Research/HFcsv's")
source("HF_analysis_functions.R")
plots<-plot.smooth.and.peaks(BM.filterwoman.list,BM.peak.from.ksmooth,reduced.BM)



#Create time series objects
# BNM.ts<-list()
# for (j in 1:length(filterwoman.list)) {
#   BNM.ts[[j]]<-ts(data = filterwoman.list[[j]][,3], start = filterwoman.list[[j]][1,1],
#                   end = filterwoman.list[[j]][nrow(filterwoman.list[[j]]),1])
# }


```

```{r output_plots, echo = FALSE, message = FALSE, warning = FALSE, fig.height=2}
plots[[1]]
plots[[2]]
plots[[3]]
plots[[4]]
plots[[5]]
plots[[6]]
plots[[7]]
plots[[8]]
plots[[9]]
plots[[10]]
plots[[11]]
plots[[12]]
plots[[13]]
plots[[14]]
plots[[15]]
plots[[16]]
plots[[17]]
plots[[18]]
plots[[19]]
plots[[20]]
plots[[21]]
plots[[22]]
plots[[23]]
plots[[24]]
plots[[25]]
plots[[26]]
plots[[27]]
plots[[28]]
plots[[29]]
plots[[30]]
plots[[31]]
plots[[32]]
plots[[33]]
```

```{r peak_tables, echo=FALSE, fig.height=6, fig.width=12}
# for (t in 1:length(BM.peak.from.ksmooth)) {
#   library(knitr)
#   if (class(BM.peak.from.ksmooth[[t]])=="NULL") print("No peaks found") else
#     peak.table<-na.omit(BM.peak.from.ksmooth[[t]])
#     print(kable(peak.table))
# }
BM.peak.from.ksmooth
# lapply(BNM.ts, function(x) acf(x))
```
